(() => {
 'use strict';
 const M=LG_PORTAL,V=LG_PORTAL_VIEWS,E=M.esc,D=M.date;
 const content=document.querySelector('#content'),nav=document.querySelector('#studentNav');
 const routes=[['home','Início'],['training','Meu treino'],['history','Histórico'],['assessments','Avaliações'],['progress','Evolução'],['anamnesis','Anamnese'],['guidance','Orientações'],['profile','Perfil']];
 let client,api,profile,route='home',revision=0,busy=false,dirty=false,timer=null,timerEnd=0;
 const button=(label,attrs='',primary=false)=>'<button type="button" class="'+(primary?'primary':'ghost')+'" '+attrs+'>'+E(label)+'</button>';
 const heading=(title,lead='')=>'<div class="ey">Minha área LG</div><h1>'+E(title)+'</h1>'+(lead?'<p class="lead">'+E(lead)+'</p>':'');
 const empty=text=>'<div class="empty">'+E(text)+'</div>';
 const at=(selector,fn)=>{const el=content.querySelector(selector);if(el)el.onclick=fn;};
 const all=(selector,fn)=>content.querySelectorAll(selector).forEach(fn);
 const active=(p)=>p.active===true;
 const stateDate=d=>{const date=d||new Date();return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);};
 function errorPanel(error,retry){content.innerHTML=heading('Não foi possível abrir esta área.')+'<p class="error" role="status">'+E(M.message(error))+'</p>'+button('Tentar novamente','id="retryPortal"');at('#retryPortal',retry);}
 function print(html){document.querySelector('#printArea').innerHTML=html;window.print();}
 function wireRoutes(){all('[data-route]',b=>{b.onclick=()=>navigate(b.dataset.route);});}
 async function navigate(next,force=false){
  if(busy)return;
  if(!routes.some(([key])=>key===next))next='home';
  if(!force&&dirty&&!window.confirm('Você tem informações não salvas. Deseja sair desta tela?'))return;
  dirty=false;route=next;const current=++revision;if(timer){clearInterval(timer);timer=null;}
  nav.querySelectorAll('[data-page]').forEach(b=>{b.setAttribute('aria-current',b.dataset.page===next?'page':'false');});
  content.innerHTML=heading(routes.find(([key])=>key===next)[1])+'<p role="status">Carregando...</p><div class="loading-line"></div>';
  history.replaceState(null,'','#'+next);
  try{await screens[next](current);if(current===revision){wireRoutes();content.focus();}}
  catch(error){if(current===revision)errorPanel(error,()=>navigate(next,true));}
 }
 function bindForm(form,operation,after){
  let committed=false;
  form.oninput=form.onchange=()=>{dirty=true;form.dataset.dirty='true';committed=false;};
  form.onsubmit=async event=>{
   event.preventDefault();if(busy||committed||!form.reportValidity())return;
   const values=Object.fromEntries(new FormData(form)),status=form.querySelector('[data-form-status]');
   const controls=[...form.querySelectorAll('input,textarea,select,button'),...nav.querySelectorAll('button'),document.querySelector('#logout')],disabled=controls.map(x=>x.disabled);
   busy=true;controls.forEach(x=>x.disabled=true);form.setAttribute('aria-busy','true');status.className='muted';status.textContent='Salvando. Aguarde a confirmação...';
   try{const saved=await operation(values);committed=true;form.dataset.dirty='false';dirty=[...content.querySelectorAll('form')].some(f=>f.dataset.dirty==='true');status.textContent='Salvo com sucesso.';try{await after(saved);}catch{status.textContent='Salvo. Atualize esta área para conferir os dados.';}}
   catch(error){status.className='error';status.textContent=M.message(error);}
   finally{busy=false;form.setAttribute('aria-busy','false');controls.forEach((x,i)=>x.disabled=disabled[i]);}
  };
 }
 const formStatus='<p data-form-status role="status" aria-live="polite"></p>';
 const actionStatus='<p id="actionStatus" role="status" aria-live="polite"></p>';
 async function action(button,operation){if(busy)return;busy=true;button.disabled=true;const status=content.querySelector('#actionStatus');try{if(status){status.className='muted';status.textContent='';}await operation();}catch(error){if(status){status.className='error';status.textContent=M.message(error);}else errorPanel(error,()=>navigate(route,true));}finally{busy=false;button.disabled=false;}}
 async function home(rev){
  const [plans,sessions,assessments,anam]=await Promise.all([api.plans(),api.sessions(),api.assessments(),api.anamnesis()]);if(rev!==revision)return;
  const current=plans.filter(active),last=sessions[0],a=assessments[0];
  content.innerHTML=heading('Olá, '+(profile.full_name.split(' ')[0]||'aluno')+'.','Seu treino, seus registros e seu acompanhamento. Escolha uma área para continuar.')+'<div class="stats"><div class="panel stat"><strong>'+current.length+'</strong><span>Plano(s) ativo(s)</span></div><div class="panel stat"><strong>'+(last?D(last.performed_at):'Ainda sem registro')+'</strong><span>Última sessão registrada</span></div><div class="panel stat"><strong>'+(a?D(a.assessed_at):'Aguardando avaliação')+'</strong><span>Última avaliação</span></div></div>'+(anam?'':'<div class="panel"><strong>Vamos completar sua anamnese?</strong><p class="muted">Seu professor precisa conhecer sua rotina, objetivos e informações de saúde.</p>'+button('Preencher anamnese','data-route="anamnesis"',true)+'</div>')+'<div class="cards"><article class="card"><span class="badge">TREINO</span><h2>'+E(current[0]?.name||'Seu próximo plano')+'</h2><p>'+E(current[0]?.goal||'Seu professor ainda não liberou um plano ativo.')+'</p>'+button('Abrir meus treinos','data-route="training"',true)+'</article><article class="card"><span class="badge">ACOMPANHAMENTO</span><h2>Minha evolução</h2><p>Compare avaliações e fotos registradas no acompanhamento.</p>'+button('Ver evolução','data-route="progress"')+'</article><article class="card"><span class="badge">PROFESSOR</span><h2>Orientações</h2><p>Consulte as recomendações registradas para você.</p>'+button('Ler orientações','data-route="guidance"')+'</article></div><p class="small">O histórico mostra apenas sessões que você registrou no sistema.</p>';
 }
 async function training(rev){
  const plans=await api.plans();if(rev!==revision)return;
  const sorted=[...plans].sort((a,b)=>Number(active(b))-Number(active(a)));
  content.innerHTML=heading('Meu treino','Planos ativos e fichas anteriores. Siga a sequência e as orientações do professor.')+(sorted.length?'<div class="list">'+sorted.map(p=>'<article class="list-row"><div><span class="badge">'+(active(p)?'Ativo':'Histórico · inativo')+'</span><strong>'+E(p.name)+'</strong><p class="small">'+E(p.goal||'Plano de treino')+' · '+D(p.starts_on)+' → '+D(p.ends_on)+'</p></div>'+button('Abrir plano','data-plan="'+E(p.id)+'"',active(p))+'</article>').join('')+'</div>':empty('Seu professor ainda não cadastrou um plano de treino.'));
  all('[data-plan]',b=>b.onclick=()=>openPlan(b.dataset.plan));
 }
 async function openPlan(id){
  if(busy)return;if(dirty&&!confirm('Deseja sair sem salvar a sessão?'))return;dirty=false;
  const rev=++revision;content.innerHTML=heading('Abrindo plano...');
  try{const bundle=await api.plan(id);if(rev!==revision)return;const p=bundle.plan;
   content.innerHTML=heading(p.name,p.goal||'Plano de treino')+'<div class="toolbar">'+button('← Meus planos','data-route="training"')+'<div class="actions">'+button('Ficha / salvar PDF','id="printTraining"')+'<span class="badge">'+(active(p)?'Plano ativo':'Histórico — registro de sessão indisponível')+'</span></div></div>'+V.note('Orientações gerais',p.notes)+'<p class="small">'+D(p.starts_on)+' → '+D(p.ends_on)+' · RIR = repetições em reserva.</p><div class="tabs" role="tablist" aria-label="Treinos do plano">'+bundle.workouts.map(w=>button(w.name,'role="tab" aria-selected="false" data-workout="'+E(w.id)+'"')).join('')+'</div><div id="workoutContent" role="tabpanel"></div>'+actionStatus;
   at('#printTraining',()=>print(V.training(bundle,profile.full_name)));wireRoutes();
   all('[data-workout]',b=>b.onclick=()=>{if(busy)return;if(dirty&&!confirm('Deseja trocar de treino sem salvar a sessão?'))return;dirty=false;drawWorkout(bundle,b.dataset.workout);});
   if(bundle.workouts.length)drawWorkout(bundle,bundle.workouts[0].id);else content.querySelector('#workoutContent').innerHTML=empty('O professor ainda não cadastrou treinos neste plano.');
  }catch(error){if(rev===revision)errorPanel(error,()=>openPlan(id));}
 }
 function timerStart(seconds){
  if(timer)clearInterval(timer);timerEnd=Date.now()+seconds*1000;
  const update=()=>{const out=content.querySelector('#restTime');if(!out){clearInterval(timer);timer=null;return;}const left=Math.max(0,Math.ceil((timerEnd-Date.now())/1000));out.textContent=Math.floor(left/60)+':'+String(left%60).padStart(2,'0');if(left===0){clearInterval(timer);timer=null;content.querySelector('#restLabel').textContent='Descanso concluído. Siga seu ritmo e a orientação do professor.';}};
  timer=setInterval(update,500);update();
 }
 function drawWorkout(bundle,id){
  const w=bundle.workouts.find(x=>x.id===id);if(!w)return;if(timer){clearInterval(timer);timer=null;}
  all('[data-workout]',b=>b.setAttribute('aria-selected',String(b.dataset.workout===id)));
  const box=content.querySelector('#workoutContent');
  box.innerHTML='<div class="panel"><h2>'+E(w.name)+'</h2>'+V.note('Orientações',w.notes)+(w.exercises.length?w.exercises.map((x,i)=>'<article class="exercise"><h3>'+(i+1)+'. '+E(x.exercise_name)+'</h3><div class="dose"><span>'+M.value(x.target_sets)+' séries</span><span>'+V.reps(x)+' repetições</span><span>RIR '+M.value(x.target_rir)+'</span><span>'+M.value(x.rest_seconds,'s')+' descanso</span></div>'+V.note('Execução',x.execution_notes)+V.note('Observações',x.notes)+(x.rest_seconds!=null?button('Iniciar descanso','data-rest="'+E(x.rest_seconds)+'"'):'')+'</article>').join(''):empty('O professor ainda está montando os exercícios.'))+'<div class="timer"><output id="restTime" aria-label="Tempo de descanso restante">0:00</output><span id="restLabel">Cronômetro opcional de descanso.</span>'+button('Parar','id="stopRest"')+'</div><div class="actions">'+(active(bundle.plan)&&w.exercises.length?button('Registrar este treino','id="recordWorkout"',true):'')+button('Ver meu histórico','data-route="history"')+'</div></div><div id="sessionFormBox"></div>';
  all('[data-rest]',b=>b.onclick=()=>timerStart(Number(b.dataset.rest)));at('#stopRest',()=>{if(timer)clearInterval(timer);timer=null;content.querySelector('#restTime').textContent='0:00';});at('#recordWorkout',()=>sessionForm(w));wireRoutes();
 }
 const setRow=(exercise,i)=>'<div class="set-row" data-set-row data-exercise="'+E(exercise.id)+'" data-set="'+i+'"><strong>'+i+'</strong><label>Carga (kg)<input data-load type="number" min="0" max="2000" step=".1" inputmode="decimal" aria-label="Carga em kg — série '+i+' de '+E(exercise.exercise_name)+'"></label><label>Repetições<input data-reps type="number" min="1" max="1000" step="1" inputmode="numeric" aria-label="Repetições — série '+i+' de '+E(exercise.exercise_name)+'"></label><label>RIR real<input data-rir type="number" min="0" max="10" step=".5" inputmode="decimal" aria-label="RIR — série '+i+' de '+E(exercise.exercise_name)+'"></label><label class="done"><input data-completed type="checkbox">Feita</label></div>';
 function sessionForm(w){
  const box=content.querySelector('#sessionFormBox');if(box.querySelector('form')){box.scrollIntoView({behavior:'smooth'});return;}
  const id=crypto.randomUUID();
  box.innerHTML='<form class="panel" id="recordSession"><h2>Registrar '+E(w.name)+'</h2><p class="muted">Informe os valores realmente realizados. Marque “Feita” nas séries concluídas. Carga e RIR podem ficar vazios.</p><div class="field"><label for="performedAt">Data e horário</label><input id="performedAt" name="performed_at" type="datetime-local" value="'+stateDate()+'" required></div>'+w.exercises.map(x=>'<section class="exercise" data-set-group="'+E(x.id)+'"><h3>'+E(x.exercise_name)+'</h3><div data-set-rows>'+Array.from({length:Math.min(20,Math.max(1,x.target_sets||1))},(_,i)=>setRow(x,i+1)).join('')+'</div>'+button('+ Adicionar série','data-add-set="'+E(x.id)+'"')+'</section>').join('')+'<div class="field"><label for="sessionNotes">Como foi o treino? Observações</label><textarea id="sessionNotes" name="notes" maxlength="5000"></textarea></div>'+formStatus+'<div class="actions"><button class="primary" type="submit">Salvar sessão e séries</button>'+button('Cancelar registro','id="cancelSession"')+'</div></form>';
  const form=box.querySelector('form');all('[data-add-set]',b=>b.onclick=()=>{const group=form.querySelector('[data-set-group="'+b.dataset.addSet+'"] [data-set-rows]'),count=group.querySelectorAll('[data-set-row]').length;if(count>=50)return;b.disabled=count>=49;group.insertAdjacentHTML('beforeend',setRow(w.exercises.find(e=>e.id===b.dataset.addSet),count+1));dirty=true;});
  at('#cancelSession',()=>{if(dirty&&!confirm('Descartar o registro não salvo?'))return;dirty=false;box.innerHTML='';});
  bindForm(form,values=>{const rows=[...form.querySelectorAll('[data-set-row]')].map(row=>({exercise_id:row.dataset.exercise,set_number:row.dataset.set,load_kg:row.querySelector('[data-load]').value,reps:row.querySelector('[data-reps]').value,rir:row.querySelector('[data-rir]').value,completed:row.querySelector('[data-completed]').checked}));return api.record(id,w.id,new Date(values.performed_at).toISOString(),values.notes,rows);},saved=>{form.innerHTML='<h2>'+ (saved.reused?'Esta sessão já estava registrada.':'Sessão registrada!')+'</h2><p>Seu professor poderá acompanhar as séries e cargas salvas.</p>'+button('Abrir histórico','data-route="history"',true);wireRoutes();});box.scrollIntoView({behavior:'smooth',block:'start'});
 }
 async function sessions(rev){
  let offset=0;const data=await api.sessions(offset);if(rev!==revision)return;
  content.innerHTML=heading('Meu histórico','Sessões e cargas que você registrou. Os planos antigos continuam disponíveis.')+'<div class="list" id="sessionHistory"></div>'+button('Carregar mais sessões','id="moreSessions"')+actionStatus;
  function append(rows){content.querySelector('#sessionHistory').insertAdjacentHTML('beforeend',rows.map(s=>'<article class="list-row"><div><strong>'+E(s.workouts?.name||'Treino')+'</strong><span class="small">'+D(s.performed_at)+' · '+new Date(s.performed_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})+' · '+E(s.workouts?.training_plans?.name||'Plano')+'</span>'+V.note('Observações',s.notes)+'</div>'+button('Ver séries','data-session="'+E(s.id)+'"')+'</article>').join(''));all('[data-session]',b=>b.onclick=()=>sessionDetail(b.dataset.session));content.querySelector('#moreSessions').hidden=rows.length<20;}
  if(data.length)append(data);else{content.querySelector('#sessionHistory').innerHTML=empty('Você ainda não registrou uma sessão. Abra Meu treino para começar.');content.querySelector('#moreSessions').hidden=true;}
  at('#moreSessions',event=>action(event.currentTarget,async()=>{const next=await api.sessions(offset+20);if(rev!==revision)return;offset+=20;append(next);}));
 }
 async function sessionDetail(id){const rev=++revision;content.innerHTML=heading('Séries realizadas');try{const data=await api.session(id);if(rev!==revision)return;content.innerHTML=heading(data.session.workouts?.name||'Sessão',D(data.session.performed_at))+button('← Histórico','data-route="history"')+V.note('Observações',data.session.notes)+V.sessionTable(data.sets);wireRoutes();}catch(e){if(rev===revision)errorPanel(e,()=>sessionDetail(id));}}
 async function assessments(rev){const data=await api.assessments();if(rev!==revision)return;content.innerHTML=heading('Minhas avaliações','Consulte os resultados registrados pelo professor e os documentos do acompanhamento.')+(data.length?'<div class="list">'+data.map(a=>'<article class="list-row"><div><strong>Avaliação · '+D(a.assessed_at)+'</strong><span class="small">Peso: '+M.value(a.weight_kg,'kg')+' · Gordura: '+M.value(a.body_fat_pct,'%')+'</span></div>'+button('Ver resultados','data-assessment="'+E(a.id)+'"',true)+'</article>').join('')+'</div>':empty('Você ainda não tem uma avaliação cadastrada.'));all('[data-assessment]',b=>b.onclick=()=>assessmentDetail(b.dataset.assessment));}
 async function assessmentDetail(id){const rev=++revision;content.innerHTML=heading('Abrindo avaliação...');try{const bundle=await api.assessment(id);if(rev!==revision)return;const html=V.assessment(bundle,profile.full_name);content.innerHTML='<div class="toolbar">'+button('← Avaliações','data-route="assessments"')+button('Relatório / salvar PDF','id="printAssessment"')+'</div><article class="panel">'+html+'</article>'+(bundle.assessment.bioimpedance_pdf_path?'<div class="actions">'+button('Abrir PDF da bioimpedância','id="openBio"',true)+'</div>':'')+actionStatus;at('#printAssessment',()=>print(html));at('#openBio',event=>action(event.currentTarget,async()=>{const url=await api.signed('assessment-documents',bundle.assessment.bioimpedance_pdf_path);const status=content.querySelector('#actionStatus');status.innerHTML='<a href="'+E(url)+'" target="_blank" rel="noopener noreferrer">PDF pronto: clique para abrir</a>'; }));wireRoutes();}catch(error){if(rev===revision)errorPanel(error,()=>assessmentDetail(id));}}
 async function progress(rev){const [data,photos]=await Promise.all([api.assessments(),api.photos()]);if(rev!==revision)return;content.innerHTML=heading('Minha evolução','Resultados e fotos registrados no acompanhamento. Compare mudanças ao longo do tempo.')+'<div class="cards"><div class="panel">'+V.progression(data,'weight_kg','Peso','kg')+'</div><div class="panel">'+V.progression(data,'body_fat_pct','Gordura corporal','%')+'</div><div class="panel">'+V.progression(data,'lean_mass_kg','Massa magra','kg')+'</div></div>'+(data.length?V.table('Histórico de avaliações',['Data','Peso (kg)','Gordura (%)','Massa magra (kg)','Massa gorda (kg)'],[...data].reverse().map(a=>[D(a.assessed_at),M.value(a.weight_kg),M.value(a.body_fat_pct),M.value(a.lean_mass_kg),M.value(a.fat_mass_kg)])):empty('Sem avaliações para comparar.'))+'<h2>Fotos de evolução</h2><p class="small">Imagens privadas, com acesso temporário. Atualize esta área se alguma imagem expirar.</p>'+button('Atualizar evolução e fotos','id="refreshPhotos"')+'<div id="photoHistory"></div>'+actionStatus;at('#refreshPhotos',()=>navigate('progress',true));const holder=content.querySelector('#photoHistory');if(!photos.length){holder.innerHTML=empty('Seu professor ainda não cadastrou fotos de evolução.');return;}const signed=await Promise.all(photos.map(async ph=>{try{return{...ph,url:await api.signed('progress-photos',ph.storage_path)}}catch{return{...ph,url:null}}}));if(rev!==revision)return;const groups={};for(const ph of signed){(groups[ph.photo_date]??=[]).push(ph);}const dates=Object.keys(groups).sort((a,b)=>b.localeCompare(a)),names={front:'Frente',back:'Costas',right:'Perfil direito',left:'Perfil esquerdo'};
  const figure=ph=>'<figure class="photo">'+(ph.url?'<img loading="lazy" src="'+E(ph.url)+'" alt="'+E(names[ph.view]||'Foto de evolução')+' · '+D(ph.photo_date)+'">':'<p class="error">Imagem indisponível. Atualize para tentar novamente.</p>')+'<figcaption>'+E(names[ph.view]||ph.view||'Foto')+' · '+D(ph.photo_date)+'</figcaption></figure>';
  const opts=dates.map(date=>'<option value="'+E(date)+'">'+D(date)+'</option>').join('');
  holder.innerHTML=(dates.length>1?'<section class="panel"><h3>Comparar antes e depois</h3><div class="form-grid"><div class="field"><label for="photoBefore">Antes</label><select id="photoBefore">'+opts+'</select></div><div class="field"><label for="photoAfter">Depois</label><select id="photoAfter">'+opts+'</select></div><div class="field"><label for="photoAngle">Ângulo</label><select id="photoAngle">'+Object.entries(names).map(([key,name])=>'<option value="'+key+'">'+name+'</option>').join('')+'</select></div></div><div id="photoComparison"></div></section>':'')+dates.map(date=>'<section><h3>'+D(date)+'</h3><div class="photo-grid">'+groups[date].map(figure).join('')+'</div></section>').join('');
  if(dates.length>1){const before=holder.querySelector('#photoBefore'),after=holder.querySelector('#photoAfter'),angle=holder.querySelector('#photoAngle');before.value=dates.at(-1);after.value=dates[0];const draw=()=>{const a=groups[before.value]?.find(ph=>ph.view===angle.value),b=groups[after.value]?.find(ph=>ph.view===angle.value);holder.querySelector('#photoComparison').innerHTML=a&&b?'<div class="compare-grid">'+figure(a)+figure(b)+'</div>':empty('Este ângulo não está disponível nas duas datas.');};before.onchange=after.onchange=angle.onchange=draw;draw();}
 }
 async function anamnesis(rev){const row=await api.anamnesis();if(rev!==revision)return;const id=row?.id||crypto.randomUUID();content.innerHTML=heading('Minha anamnese','Revise suas informações e atualize o que mudou. Elas ajudam o professor a planejar o acompanhamento.')+'<form id="anamForm" class="panel"><p class="small">'+(row?'Última atualização: '+D(row.updated_at):'Primeiro preenchimento')+'</p><div class="form-grid">'+M.anamFields.map(([key,label])=>'<div class="field '+(['training_goal','pain_injuries','medical_conditions','additional_notes'].includes(key)?'full':'')+'"><label for="anam_'+key+'">'+E(label)+'</label><textarea id="anam_'+key+'" name="'+key+'" maxlength="5000" '+(key==='training_goal'?'required':'')+'>'+E(row?.[key]??row?.answers?.[key]??'')+'</textarea></div>').join('')+'<div class="field"><label for="sleepHours">Horas médias de sono</label><input type="number" id="sleepHours" name="sleep_hours" min="0" max="24" step=".5" value="'+E(row?.sleep_hours??'')+'"></div></div><h2>PAR-Q · saúde e segurança</h2><p class="small">Respostas positivas sinalizam informações a revisar com o professor; não são diagnósticos.</p>'+M.parqQuestions.map((question,i)=>{const answer=row?.parq_answers?.['q'+(i+1)]?.answer??row?.answers?.parq_answers?.['q'+(i+1)]?.answer??'';return '<div class="parq-question"><label for="parq_'+i+'">'+E(question)+'</label><select id="parq_'+i+'" name="parq_'+i+'" required><option value="">Selecione</option><option value="no" '+(answer==='no'?'selected':'')+'>Não</option><option value="yes" '+(answer==='yes'?'selected':'')+'>Sim</option></select></div>';}).join('')+'<label class="check-label"><input name="reviewed" type="checkbox" required><span>Revisei estas informações e entendo que serão usadas pelo professor no meu acompanhamento.</span></label>'+formStatus+'<button class="primary" type="submit">Salvar minha anamnese</button></form>';bindForm(content.querySelector('#anamForm'),values=>api.saveAnam(values,id,row?.answers||{}),()=>{content.querySelector('#anamForm [data-form-status]').textContent='Anamnese salva e disponível para seu professor.';});}
 async function guidance(rev){const rows=await api.guidance();if(rev!==revision)return;content.innerHTML=heading('Minhas orientações','Recomendações registradas pelo professor para seu acompanhamento.')+(rows.length?'<div class="list">'+rows.map(row=>'<article class="panel"><p class="small">'+D(row.created_at)+'</p><h2>'+E(row.title)+'</h2><div class="guidance-body">'+E(row.body)+'</div></article>').join('')+'</div>':empty('Seu professor ainda não registrou orientações para você.'));}
 async function myProfile(rev){const data=await api.profile();if(rev!==revision)return;profile=data;content.innerHTML=heading('Meu perfil','Seu cadastro e acesso LG.')+'<div class="panel"><p><strong>E-mail de acesso:</strong> '+E(data.email||'Não informado')+'</p><p class="small">Para corrigir o e-mail ou informações do acompanhamento, procure o professor.</p><p><strong>Objetivo:</strong> '+E(data.goal||'Não informado')+' · <strong>Início:</strong> '+D(data.start_date)+'</p><form id="profileForm"><div class="form-grid"><div class="field full"><label for="profileName">Nome completo</label><input id="profileName" name="full_name" maxlength="160" value="'+E(data.full_name)+'" required autocomplete="name"></div><div class="field"><label for="profilePhone">Telefone</label><input id="profilePhone" name="phone" maxlength="40" value="'+E(data.phone||'')+'" autocomplete="tel"></div><div class="field"><label for="profileBirth">Nascimento</label><input id="profileBirth" name="birth_date" type="date" min="1900-01-01" max="'+stateDate().slice(0,10)+'" value="'+E(data.birth_date||'')+'"></div><div class="field"><label for="profileSex">Sexo biológico</label><select id="profileSex" name="sex"><option value="">Não informado</option><option value="female" '+(data.sex==='female'?'selected':'')+'>Feminino</option><option value="male" '+(data.sex==='male'?'selected':'')+'>Masculino</option></select></div></div>'+formStatus+'<button type="submit" class="primary">Salvar meus dados</button></form></div><form id="passwordUpdate" class="panel" style="margin-top:20px"><h2>Alterar minha senha</h2><div class="form-grid"><div class="field"><label for="profilePassword">Nova senha</label><input id="profilePassword" name="password" type="password" minlength="8" maxlength="128" required autocomplete="new-password"></div><div class="field"><label for="profileConfirm">Confirmar senha</label><input id="profileConfirm" name="confirm_password" type="password" minlength="8" maxlength="128" required autocomplete="new-password"></div></div>'+formStatus+'<button type="submit" class="ghost">Salvar nova senha</button></form>';bindForm(content.querySelector('#profileForm'),values=>api.updateProfile(values),saved=>{profile={...profile,...saved};content.querySelector('#profileForm [data-form-status]').textContent='Seus dados foram atualizados.';});bindForm(content.querySelector('#passwordUpdate'),values=>api.password(values.password,values.confirm_password),()=>{const form=content.querySelector('#passwordUpdate');form.reset();form.querySelector('[data-form-status]').textContent='Senha alterada com sucesso.';});}
 const screens={home,training,history:sessions,assessments,progress,anamnesis,guidance,profile:myProfile};
 async function boot(){try{client=LG_AUTH.createClient();const access=await LG_AUTH.access(client);if(access.profile.role==='trainer')return location.replace('./admin.html');api=M.createApi(client,access.user.id);profile=await api.profile();nav.innerHTML=routes.map(([key,label],i)=>button(label,'data-page="'+key+'" aria-current="false"')).join('');nav.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));await navigate(location.hash.slice(1)||'home',true);}catch(error){if(LG_AUTH.sessionExpired(error))return location.replace('./index.html');content.innerHTML=heading('Não foi possível abrir sua área.')+'<p class="error" role="status">'+E(LG_AUTH.message(error))+'</p>'+button('Tentar novamente','id="retryPortal"');at('#retryPortal',()=>location.reload());}}
 document.querySelector('#logout').onclick=async event=>{if(busy)return;if(dirty&&!confirm('Sair sem salvar as informações desta tela?'))return;const b=event.currentTarget;b.disabled=true;try{const result=await LG_AUTH.deadline(()=>client.auth.signOut());if(result.error)throw result.error;content.textContent='';document.querySelector('#printArea').textContent='';location.replace('./index.html');}catch{b.disabled=false;content.insertAdjacentHTML('afterbegin','<p class="error" role="status">Não foi possível sair. Confira a conexão e tente novamente.</p>');}};
 window.addEventListener('beforeunload',event=>{if(dirty||busy){event.preventDefault();event.returnValue='';}});
 window.addEventListener('afterprint',()=>{document.querySelector('#printArea').textContent='';});
 boot();
})();
