(()=>{
const css=`.attention-panel{border:1px solid #866f38;background:#211b10;padding:16px;margin:16px 0}.attention-panel h3{margin:0 0 10px;color:#e7ca7c}.attention-list{display:grid;gap:7px}.attention-item{padding:9px 11px;border-left:3px solid #866f38;background:#18150f}.attention-item.high{border-left-color:#b85d5d}.attention-count{display:inline-flex;min-width:22px;height:22px;align-items:center;justify-content:center;border-radius:99px;background:#866f38;color:#fff;font-size:11px;margin-left:6px}`;let st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
const baseAlunos=window.alunos,baseHub=window.openStudentHub;
const getData=async()=>{let [an,as,tp]=await Promise.all([sb.from('anamneses').select('*'),sb.from('assessments').select('student_id,assessed_at').order('assessed_at',{ascending:false}),sb.from('training_plans').select('student_id,active,ends_on')]);return{anam:an.data||[],ass:as.data||[],plans:tp.data||[]}};
const days=d=>d?Math.floor((Date.now()-new Date(String(d).slice(0,10)+'T12:00:00').getTime())/86400000):null;
const aVal=(a,k)=>a?.[k]??a?.answers?.[k]??'';
const flags=(sid,d)=>{let a=d.anam.find(x=>x.student_id===sid),ass=d.ass.filter(x=>x.student_id===sid),plan=d.plans.find(x=>x.student_id===sid&&x.active),f=[];if(!a)f.push({t:'Anamnese pendente',high:false});if(!ass.length)f.push({t:'Sem avaliação física',high:false});else if(days(ass[0].assessed_at)>60)f.push({t:'Última avaliação há '+days(ass[0].assessed_at)+' dias',high:false});if(!plan)f.push({t:'Sem plano de treino ativo',high:false});if(a){let pq=a.parq_answers||a.answers?.parq_answers||{};let yes=Object.values(pq).filter(x=>x?.answer==='yes').length;if(yes)f.push({t:'PAR-Q: '+yes+' resposta(s) “Sim” — revisar antes da prescrição',high:true});if(String(aVal(a,'pain_injuries')).trim())f.push({t:'Dor/lesão informada na anamnese — revisar',high:true});if(String(aVal(a,'medical_conditions')).trim())f.push({t:'Condição de saúde informada — revisar',high:true});if(String(aVal(a,'medications')).trim())f.push({t:'Uso de medicamento informado — revisar',high:false})}return f};
window.alunos=async function(){await baseAlunos();let d=await getData();document.querySelectorAll('#studentList .student-card').forEach(card=>{let b=card.querySelector('button[onclick^="openStudentHub"]');if(!b)return;let m=b.getAttribute('onclick').match(/'([^']+)'/);if(!m)return;let f=flags(m[1],d);if(f.length){let badges=card.querySelector('.student-badges');badges.insertAdjacentHTML('beforeend','<span class="student-badge warn">Atenção '+f.length+'</span>')}});let total=students.reduce((n,s)=>n+(flags(s.id,d).length?1:0),0),kpis=document.querySelector('.student-kpis');if(kpis)kpis.insertAdjacentHTML('beforeend','<div class="student-kpi"><strong>'+total+'</strong>Precisam de atenção</div>')};
window.openStudentHub=async function(id,tab='overview'){await baseHub(id,tab);let d=await getData(),f=flags(id,d);if(!f.length)return;let tabs=document.querySelector('.student-hub-tabs');if(!tabs)return;tabs.insertAdjacentHTML('beforebegin','<div class="attention-panel"><h3>Pontos para sua revisão profissional <span class="attention-count">'+f.length+'</span></h3><div class="attention-list">'+f.map(x=>'<div class="attention-item '+(x.high?'high':'')+'">'+esc(x.t)+'</div>').join('')+'</div><p class="muted" style="margin-bottom:0">Os avisos organizam informações e pendências; não representam diagnóstico.</p></div>')};
const baseDashboard=window.dashboard;window.dashboard=async function(){await baseDashboard();let d=await getData();await loadStudents();let attention=students.filter(s=>flags(s.id,d).length).length,stats=document.querySelector('.stats');if(stats)stats.insertAdjacentHTML('beforeend','<div class="stat"><strong>'+attention+'</strong>alunos para revisar</div>')};
})();