(()=>{
const baseTreinos=window.treinos;
window.treinos=async function(){await baseTreinos();let toolbar=view.querySelector('.toolbar'),primary=toolbar?.querySelector('.primary');if(toolbar&&primary){let wrap=document.createElement('div');wrap.className='report-actions';let model=document.createElement('button');model.className='ghost';model.textContent='Copiar modelo LG';model.onclick=copyLGTrainingTemplate;let imp=document.createElement('button');imp.className='ghost';imp.textContent='Importar treino';imp.onclick=()=>trainingImportForm();wrap.append(model,imp,primary);toolbar.appendChild(wrap)}};

async function loadPlanForAction(id){let {data,error}=await sb.from('training_plans').select('id,name,active,student_id').eq('id',id).single();if(error)throw error;return data}

window.toggleTrainingPlanActive=async function(id){try{let plan=await loadPlanForAction(id),next=!plan.active,msg=next?'Reativar este plano de treino?':'Desativar este plano?\n\nEle continuará salvo no histórico e poderá ser reativado depois.';if(!confirm(msg))return;let {error}=await sb.from('training_plans').update({active:next}).eq('id',id);if(error)throw error;toast(next?'Plano reativado':'Plano desativado e mantido no histórico');await openTrainingPlan(id)}catch(e){toast('Não foi possível alterar o plano: '+e.message)}};

window.deleteTrainingPlan=async function(id){try{let plan=await loadPlanForAction(id);let first=confirm('Excluir permanentemente o plano “'+plan.name+'”?\n\nUse esta opção apenas para testes ou cadastros incorretos. Se houver sessões registradas, a exclusão será bloqueada para preservar o histórico.');if(!first)return;let typed=prompt('Para confirmar a exclusão permanente, digite EXCLUIR:');if(typed!=='EXCLUIR')return toast('Exclusão cancelada');let {error}=await sb.rpc('delete_training_plan',{p_plan_id:id});if(error)throw error;toast('Plano excluído com sucesso');await treinos()}catch(e){toast('Exclusão cancelada: '+e.message)}};

const baseOpen=window.openTrainingPlan;
window.openTrainingPlan=async function(id){await baseOpen(id);let toolbar=view.querySelector('.toolbar');if(toolbar){let {data:plan}=await sb.from('training_plans').select('active').eq('id',id).single();let a=document.createElement('div');a.className='report-actions';a.innerHTML='<button class="ghost" id="trainingView">Visualizar ficha</button><button class="primary" id="trainingPdf">Gerar PDF</button><button class="ghost" id="trainingToggle">'+(plan?.active===false?'Reativar plano':'Desativar plano')+'</button><button class="ghost" id="trainingDelete" style="border-color:#b42318;color:#b42318">Excluir plano</button>';toolbar.appendChild(a);a.querySelector('#trainingView').onclick=()=>trainingReport(id,false);a.querySelector('#trainingPdf').onclick=()=>trainingReport(id,true);a.querySelector('#trainingToggle').onclick=()=>toggleTrainingPlanActive(id);a.querySelector('#trainingDelete').onclick=()=>deleteTrainingPlan(id)}};
})();