// Exercise the actual Anamneses navigation route with the real table's column names.
import fs from 'node:fs';
import assert from 'node:assert/strict';
const {Window}=await import(process.env.HAPPY_DOM_ENTRY||'happy-dom');
const read=f=>fs.readFileSync(new URL('../'+f,import.meta.url),'utf8');
const w=new Window({url:'https://example.test/admin.html',settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true,disableComputedStyleRendering:true}});
w.document.write(read('admin.html').replace(/<script\b[\s\S]*?<\/script>/g,''));
const student={id:'qa-student',full_name:'Aluno <QA>',role:'student',active:true};
const row={id:'qa-anam',student_id:student.id,updated_at:'2026-10-10T12:00:00Z',submitted_at:'2026-10-01T12:00:00Z',answers:{questionnaire_version:2,training_goal:'Objetivo sintético'}};
let records=[row],failure=false,queries=[];
const columns=new Set(['id','student_id','answers','submitted_at','updated_at']);
const client={rpc:async()=>({data:[]}),from(table){let selected='',ordered='',single=false;const q={select(fields){selected=fields;return this;},eq(){return this;},order(field){ordered=field;return this;},limit(){return this;},maybeSingle(){single=true;return this;},then(resolve,reject){queries.push({table,selected,ordered});const error=table==='anamneses'&&(!columns.has(ordered)||failure)?{message:failure?'QA connection failure':'column anamneses.'+ordered+' does not exist'}:null;return Promise.resolve({error,data:error?null:table==='profiles'?[student]:table==='anamneses'?single?records[0]??null:records:[]}).then(resolve,reject);}};return q;}};
w.LG_AUTH={createClient:()=>client};w.eval(read('anamnesis-schema.js'));
let exports=0;w.LG_ANAM_PDF={open:(a,s)=>{assert.equal(a.student_id,s.id);exports++;}};
const script=[...read('admin.html').matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)].find(x=>!x[1].includes('src='))[2];
w.eval(script.replace('boot();','').replace('const sb=','var sb=').replace('const esc=','var esc=').replace('let me=null,students=[]','var me=null,students=[]'));
w.document.querySelector('#nav').innerHTML='<button data-page="Anamneses">Anamneses</button><button data-page="Alunos">Alunos</button>';
const settle=async()=>{for(let i=0;i<8;i++)await new Promise(r=>setTimeout(r,0));};
await w.go('Anamneses');let view=w.document.querySelector('#view');
assert.ok(!view.textContent.includes('Erro ao carregar'),'Actual route must not order anamneses by absent created_at');
assert.match(view.textContent,/ANAMNESES/);assert.match(view.textContent,/Aluno <QA>/);assert.equal(view.querySelector('b QA'),null);
assert.equal(queries.filter(q=>q.table==='anamneses').at(-1).ordered,'updated_at');assert.equal(queries.filter(q=>q.table==='anamneses').at(-1).selected,'id,student_id,submitted_at,updated_at');
records=[row,{...row,id:'old-qa',updated_at:'2026-09-01T12:00:00Z'}];await w.go('Anamneses');assert.equal(view.querySelectorAll('[data-anam-student]').length,1);records=[row];
assert.equal(view.querySelector('[data-anam-student]').type,'button');view.querySelector('[data-anam-student]').click();await settle();
assert.equal(w.document.querySelector('#modal').open,true);assert.match(w.document.querySelector('#form').textContent,/Objetivo sintético/);w.document.querySelector('#anamModalPdf').click();assert.equal(exports,1);w.document.querySelector('#modal').close();
records=[];await w.go('Anamneses');assert.match(view.textContent,/Nenhuma anamnese/);assert.equal(view.querySelector('[data-anam-student]'),null);
failure=true;await w.go('Anamneses');assert.match(view.textContent,/Erro ao carregar/);failure=false;records=[row];await w.go('Anamneses');assert.ok(view.querySelector('[data-anam-student]'));
console.log('PASS: actual Anamneses route, strict real-schema ordering, escaped student name, view report/PDF, empty list and query failure/retry');
await w.happyDOM.close();
