const {test}=require('node:test'),assert=require('node:assert/strict'),B=require('../backup-crypto.js');
const pass='QA-only-strong-password-123';
function snapshot(){return {format:'lg-system-snapshot',version:1,project_ref:'ziunjhebdkqdmvsrjxhm',created_at:new Date().toISOString(),tables:Object.fromEntries(B.TABLES.map(t=>[t,[]])),private_notes:[],storage_files:[]};}
function payload(){return {format:'lg-encrypted-app-content',version:1,snapshot:snapshot(),attachments:[]};}
test('encrypted roundtrip excludes plaintext and uses random salt/IV',async()=>{const p=payload();p.snapshot.tables.profiles.push({id:'qa',full_name:'PRIVATE QA NAME'});const one=await B.encrypt(p,pass),two=await B.encrypt(p,pass);assert.ok(!one.includes('PRIVATE QA NAME'));assert.notEqual(one,two);assert.deepEqual(await B.decrypt(one,pass),p);});
test('wrong password and tampering are rejected',async()=>{const s=await B.encrypt(payload(),pass);await assert.rejects(B.decrypt(s,'Different-password-123'),/Senha incorreta/);const e=JSON.parse(s);e.ciphertext=(e.ciphertext[0]==='A'?'B':'A')+e.ciphertext.slice(1);await assert.rejects(B.decrypt(JSON.stringify(e),pass),/arquivo alterado/);});
test('unsupported formats and attacker-controlled KDF work are rejected',async()=>{const e=JSON.parse(await B.encrypt(payload(),pass));e.iterations=2147483647;await assert.rejects(B.decrypt(JSON.stringify(e),pass),/incompatível/);await assert.rejects(B.decrypt('{}',pass),/incompatível/);await assert.rejects(B.decrypt('not JSON',pass),/inválido/);});
test('short or oversized passwords rejected',()=>{assert.throws(()=>B.password('123'),/12 a 256/);assert.throws(()=>B.password('x'.repeat(257)),/12 a 256/);});
test('unknown table or project rejected',()=>{const s=snapshot();s.tables.auth_users=[];assert.throws(()=>B.snapshot(s),/Tabelas/);delete s.tables.auth_users;s.project_ref='foreign';assert.throws(()=>B.snapshot(s),/incompatível/);});
test('IDs and orphaned references validated',()=>{const s=snapshot();s.tables.profiles=[{id:'one'},{id:'one'}];assert.throws(()=>B.snapshot(s),/duplicado/);s.tables.profiles=[{id:'one'}];s.tables.training_plans=[{id:'p',student_id:'foreign'}];assert.throws(()=>B.snapshot(s),/Referência/);});
test('private notes must refer to backed-up profile',()=>{const s=snapshot();s.private_notes=[{profile_id:'unknown',observations:'Private'}];assert.throws(()=>B.snapshot(s),/privada/);});
test('binary file survives encrypted roundtrip with checksum',async()=>{const p=payload(),data=new Uint8Array([0,255,1,128,65]);const f={bucket_id:'progress-photos',name:'qa/image.png'};p.snapshot.storage_files=[f];p.attachments=[{...f,size:data.length,sha256:await B.sha256(data),data:B.b64(data)}];assert.equal((await B.validate(p)).files,1);assert.deepEqual(await B.decrypt(await B.encrypt(p,pass),pass),p);p.attachments[0].sha256='0'.repeat(64);await assert.rejects(B.validate(p),/Integridade/);});
test('missing, extra, duplicated and traversal files rejected',async()=>{const p=payload();p.snapshot.storage_files=[{bucket_id:'assessment-docs',name:'qa/file.pdf'}];await assert.rejects(B.validate(p),/faltam/);p.snapshot.storage_files[0].name='../file.pdf';await assert.rejects(B.validate(p),/Referência/);p.snapshot.storage_files[0].name='qa/file.pdf';p.snapshot.storage_files.push(p.snapshot.storage_files[0]);await assert.rejects(B.validate(p),/duplicado/);});
test('collection includes all storage files and rejects failed download',async()=>{const s=snapshot();s.storage_files=[{bucket_id:'progress-photos',name:'qa/photo.png'}];let fail=false;const client={rpc:async()=>({data:s}),storage:{from:()=>({download:async()=>fail?{error:new Error('unavailable')}:{data:new Blob([new Uint8Array([1,2,3])])}})}};assert.equal((await B.validate(await B.collect(client))).files,1);fail=true;await assert.rejects(B.collect(client),/Falha ao copiar/);});
test('collection rejects mid-backup storage changes',async()=>{const s=snapshot();let calls=0;const client={rpc:async()=>({data:++calls===1?s:{...s,storage_files:[{bucket_id:'assessment-docs',name:'new.pdf'}]}})};await assert.rejects(B.collect(client),/mudaram/);});
test('collection rejects unauthorized RPC without disclosing server details',async()=>{await assert.rejects(B.collect({rpc:async()=>({error:{message:'sensitive SQL'}})}),/professor ativo/);});
test('malformed base64 and nonce rejected',async()=>{const e=JSON.parse(await B.encrypt(payload(),pass));e.iv='%%%';await assert.rejects(B.decrypt(JSON.stringify(e),pass),/inválido/);});
