const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function fixture(options={}){
 const writes=[],calls=[];let failSave=options.failSave;
 const uid='student',user={id:uid,email:'student@example.invalid'};
 const c={URL,Date,AbortController,setTimeout,clearTimeout,crypto:{randomUUID:()=> 'anam-id'},navigator:{onLine:true}};c.window=c;
 vm.createContext(c);for(const f of ['auth-client.js','portal-model.js','onboarding-model.js'])vm.runInContext(fs.readFileSync(__dirname+'/../'+f,'utf8'),c);
 const q=(table)=>{let row;const builder={select(){return this;},eq(){return this;},order(){return this;},limit(){return this;},abortSignal(){return this;},upsert(value){row=value;writes.push(value);return this;},then(resolve,reject){const result=table==='profiles'?{data:options.profile||{id:uid,role:'student',active:true}}:row?(failSave?{error:{code:'42501'}}:options.unconfirmed?{data:null}:{data:{id:row.id,student_id:row.student_id}}):{data:options.existing||null};return Promise.resolve(result).then(resolve,reject);},single(){return this;},maybeSingle(){return this;}};return builder;};
 const client={auth:{signUp:async args=>{calls.push(['signup',args]);if(options.signupThrows)throw{code:'request_timeout'};if(options.signupError)return{error:options.signupError};return{data:{user,session:options.pending?null:{}}};},signInWithPassword:async args=>{calls.push(['login',args]);return options.loginError?{error:options.loginError}:{data:{user,session:{}}};},getUser:async()=>{calls.push(['identity']);return options.identityError?{error:{code:'session_expired'}}:{data:{user:options.foreign?{id:'foreign',email:user.email}:options.foreignEmail?{id:uid,email:'foreign@example.invalid'}:user}};}},from:q};
 return{c,flow:c.LG_ONBOARDING.createFlow(client),calls,writes,repair:()=>failSave=false};
}
const values=()=>({full_name:'Aluno QA',birth_date:'1996-01-11',sex:'male',email:'student@example.invalid',password:'Strong-Test-123',confirm_password:'Strong-Test-123',training_goal:'Força',sleep_hours:'7.5',reviewed:'on',...Object.fromEntries(Array.from({length:7},(_,i)=>['parq_'+i,'no']))});
test('signup confirms own anamnesis write and submission timestamp',async()=>{const f=fixture();assert.equal((await f.flow.submit(values())).status,'completed');assert.equal(f.writes[0].student_id,'student');assert.equal(f.writes[0].id,'anam-id');assert.equal(f.writes[0].sleep_hours,7.5);assert.ok(f.writes[0].submitted_at);assert.equal(f.calls[0][1].options.data.medical_conditions,undefined);});
test('confirmation pending is not success and sends no clinical write',async()=>{const f=fixture({pending:true});assert.equal((await f.flow.submit(values())).status,'pending_confirmation');assert.equal(f.writes.length,0);assert.equal(f.flow.state().completed,false);assert.equal(f.flow.state().loginRequired,true);assert.equal((await f.flow.submit(values())).status,'completed');assert.equal(f.calls.filter(x=>x[0]==='signup').length,1);assert.equal(f.calls.filter(x=>x[0]==='login').length,1);});
test('existing account authenticates without signup or new profile',async()=>{const f=fixture();await f.flow.submit({...values(),existing_access:'on',confirm_password:''});assert.equal(f.calls[0][0],'login');assert.equal(f.calls.filter(x=>x[0]==='signup').length,0);});
test('failed save retries same ID without re-registering',async()=>{const f=fixture({failSave:true});await assert.rejects(()=>f.flow.submit(values()));assert.equal(f.flow.state().busy,false);f.repair();await f.flow.submit(values());assert.equal(f.writes.length,2);assert.equal(f.writes[0].id,f.writes[1].id);assert.equal(f.calls.filter(x=>x[0]==='signup').length,1);});
test('lost signup response is resumed by login',async()=>{const f=fixture({signupThrows:true});await assert.rejects(()=>f.flow.submit(values()));await f.flow.submit(values());assert.equal(f.calls.filter(x=>x[0]==='signup').length,1);assert.equal(f.writes.length,1);});
for(const[key,value]of [['training_goal',''],['reviewed',''],['parq_0',''],['sleep_hours','25'],['birth_date','2026-02-30'],['birth_date','2099-01-01'],['full_name',''],['sex','invalid'],['email','invalid'],['password','short'],['confirm_password','different']])test('invalid '+key+' creates no access or anamnesis',async()=>{const f=fixture();await assert.rejects(()=>f.flow.submit({...values(),[key]:value}));assert.equal(f.calls.length,0);assert.equal(f.writes.length,0);});
for(const options of [{foreign:true},{foreignEmail:true},{profile:{id:'student',role:'trainer',active:true}},{profile:{id:'student',role:'student',active:false}},{identityError:true},{existing:{id:'other-anam',student_id:'student'}}])test('unsafe identity/profile/existing record '+JSON.stringify(options)+' cannot write',async()=>{const f=fixture(options);await assert.rejects(()=>f.flow.submit(values()));assert.equal(f.writes.length,0);assert.equal(f.flow.state().completed,false);});
test('lost acknowledgement record reuses own ID and preserves legacy answers',async()=>{const f=fixture({existing:{id:'anam-id',answers:{legacy:'test'}}});await f.flow.submit(values());assert.equal(f.writes[0].answers.legacy,'test');});
test('unconfirmed write cannot claim success',async()=>{const f=fixture({unconfirmed:true});await assert.rejects(()=>f.flow.submit(values()),e=>e.code==='unconfirmed');assert.equal(f.flow.state().completed,false);});
test('confirmed flow ignores repeated submission',async()=>{const f=fixture();await f.flow.submit(values());await f.flow.submit(values());assert.equal(f.writes.length,1);});
test('pending flow rejects changed email',async()=>{const f=fixture({pending:true});await f.flow.submit(values());await assert.rejects(()=>f.flow.submit({...values(),email:'other@example.invalid'}),e=>e.code==='identity_changed');assert.equal(f.writes.length,0);});
test('known signup validation failure allows corrected creation',async()=>{const f=fixture({signupError:{code:'weak_password'}});await assert.rejects(()=>f.flow.submit(values()));assert.equal(f.flow.state().loginRequired,false);});
test('parallel submission sends only one signup and write',async()=>{const f=fixture();const pending=f.flow.submit(values());assert.equal((await f.flow.submit(values())).status,'busy');await pending;assert.equal(f.writes.length,1);});
test('confirmation failure keeps pending without a clinical write',async()=>{const f=fixture({pending:true,loginError:{code:'email_not_confirmed'}});await f.flow.submit(values());await assert.rejects(()=>f.flow.submit(values()));assert.equal(f.writes.length,0);assert.equal(f.flow.state().busy,false);});
