const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const student='11111111-1111-4111-8111-111111111111';
async function backend(options={}){
 const {passwordLinkHandler}=await import('../supabase/functions/student-password-link/handler.mjs');const calls=[];
 const profile=value=>({select(){return this},eq(){return this},maybeSingle:async()=>({data:value})});
 const handler=passwordLinkHandler({now:()=>100000,
  caller:()=>({auth:{getUser:async()=>options.invalidSession?{error:{}}:{data:{user:{id:'teacher'}}}},from:()=>profile(options.trainer||{role:'trainer',active:true})}),
  admin:{from:()=>profile(options.student||{id:student,role:'student',active:true}),auth:{admin:{getUserById:async id=>options.missingAccount?{error:{}}:{data:{user:{id,email:'qa@example.test',recovery_sent_at:options.recent?'1970-01-01T00:01:30Z':undefined}}},generateLink:async args=>{calls.push(args);return options.generateError?{error:{}}:{data:{user:{id:options.wrongId?'other':student},properties:{hashed_token:'a'.repeat(64)}}};}}}}
 });
 return {handler,calls};
}
function request(options={}){return new Request('https://example.test',{method:options.method||'POST',headers:{Authorization:options.noAuth?'':'Bearer valid',Origin:options.origin||'https://telagomidia.github.io','Content-Type':'application/json'},body:options.method==='OPTIONS'||options.method==='GET'?undefined:JSON.stringify({student_id:options.id||student})});}
test('server generates recovery for authoritative account and fixed site without sending mail',async()=>{const s=await backend();const response=await s.handler(request());assert.equal(response.status,200);const data=await response.json();assert.ok(data.url.startsWith('https://telagomidia.github.io/Luan-Guiron-/senha.html#token_hash='));assert.equal(s.calls[0].type,'recovery');assert.equal(s.calls[0].email,'qa@example.test');assert.equal(response.headers.get('Cache-Control'),'no-store');assert.deepEqual(Object.keys(data),['url']);});
for(const [name,opts,status] of [['missing bearer',{},401],['invalid session',{invalidSession:true},401],['student caller',{trainer:{role:'student',active:true}},403],['inactive trainer',{trainer:{role:'trainer',active:false}},403],['inactive student',{student:{role:'student',active:false}},400],['trainer target',{student:{role:'trainer',active:true}},400],['missing auth account',{missingAccount:true},400],['recent link',{recent:true},429],['auth generation failure',{generateError:true},502],['wrong returned account',{wrongId:true},502]])test('server rejects '+name,async()=>{const s=await backend(opts);const response=await s.handler(request({noAuth:name==='missing bearer'}));assert.equal(response.status,status);if(!['auth generation failure','wrong returned account'].includes(name))assert.equal(s.calls.length,0);});
test('server rejects invalid ID, disallowed origin and wrong method',async()=>{const s=await backend();for(const [options,status] of [[{id:'bad'},400],[{origin:'https://evil.test'},403],[{method:'GET'},405]])assert.equal((await s.handler(request(options))).status,status);assert.equal(s.calls.length,0);});
test('CORS preflight does not require login or generate token',async()=>{const s=await backend();assert.equal((await s.handler(request({method:'OPTIONS',noAuth:true}))).status,200);assert.equal(s.calls.length,0);});
function page(options={}){
 const nodes={};for(const id of ['passwordStatus','verifyLink','passwordForm','newPassword','confirmPassword','savePassword','togglePassword'])nodes[id]={value:'',textContent:'',type:'password',disabled:false,hidden:false,attrs:{},setAttribute(k,v){this.attrs[k]=v;},focus(){},reportValidity(){return options.valid!==false;}};
 const calls=[],historyCalls=[];let resolve;
 const auth={verifyOtp:async args=>{calls.push({verify:args});return options.invalidToken?{error:{}}:{data:{session:{access_token:'test'},user:{id:'student'}}};},getUser:async()=>({data:{user:{id:options.changedIdentity?'other':'student'}}}),updateUser:args=>{calls.push({update:args});if(options.pending)return new Promise(r=>resolve=r);return Promise.resolve(options.updateError?{error:{code:options.updateError}}:{data:{user:{id:'student'}}});},signOut:async args=>calls.push({signOut:args})};
 const c={document:{querySelector:s=>nodes[s.slice(1)]},location:{hash:options.noToken?'':'#token_hash='+'a'.repeat(64),pathname:'/Luan-Guiron-/senha.html'},history:{replaceState:(...args)=>historyCalls.push(args)},URLSearchParams,AbortSignal,fetch:()=>{},LG_CONFIG:{supabaseUrl:'https://project.test',supabaseKey:'publishable'},LG_AUTH:{deadline:operation=>operation()},supabase:{createClient:(url,key,config)=>{calls.push({config});return{auth};}}};vm.createContext(c);vm.runInContext(fs.readFileSync(__dirname+'/../password-page.js','utf8'),c);
 return {nodes,calls,historyCalls,c,resolveUpdate:value=>resolve(value)};
}
test('password page does not verify token until explicit click and isolates session',()=>{const s=page();assert.equal(s.calls.filter(x=>x.verify).length,0);assert.equal(s.calls[0].config.auth.persistSession,false);assert.equal(s.calls[0].config.auth.detectSessionInUrl,false);assert.equal(s.calls[0].config.auth.storageKey,'lg-password-recovery');assert.equal(s.historyCalls[0][2],'/Luan-Guiron-/senha.html');});
test('missing token prevents client and password change',()=>{const s=page({noToken:true});assert.equal(s.calls.length,0);assert.equal(s.nodes.verifyLink.hidden,true);});
test('invalid token never exposes save form',async()=>{const s=page({invalidToken:true});await s.nodes.verifyLink.onclick();assert.equal(s.nodes.passwordStatus.className,'error');assert.equal(s.calls.filter(x=>x.update).length,0);});
test('verify checks server identity before exposing form',async()=>{const s=page({changedIdentity:true});await s.nodes.verifyLink.onclick();assert.equal(s.nodes.verifyLink.hidden,false);assert.match(s.nodes.passwordStatus.textContent,/inválido/);});
test('mismatched passwords do not call updateUser',async()=>{const s=page();await s.nodes.verifyLink.onclick();s.nodes.newPassword.value='password1';s.nodes.confirmPassword.value='password2';await s.nodes.passwordForm.onsubmit({preventDefault(){}});assert.equal(s.calls.filter(x=>x.update).length,0);});
test('successful save preserves literal password and clears fields then signs out locally',async()=>{const s=page();await s.nodes.verifyLink.onclick();s.nodes.newPassword.value=s.nodes.confirmPassword.value='  password1  ';await s.nodes.passwordForm.onsubmit({preventDefault(){}});assert.equal(s.calls.find(x=>x.update).update.password,'  password1  ');assert.equal(s.nodes.newPassword.value,'');assert.equal(s.nodes.confirmPassword.value,'');assert.equal(s.calls.find(x=>x.signOut).signOut.scope,'local');assert.match(s.nodes.passwordStatus.textContent,/Senha definida/);});
test('repeated submit sends one password update',async()=>{const s=page({pending:true});await s.nodes.verifyLink.onclick();s.nodes.newPassword.value=s.nodes.confirmPassword.value='password1';const event={preventDefault(){}};const p=s.nodes.passwordForm.onsubmit(event);await Promise.resolve();await s.nodes.passwordForm.onsubmit(event);assert.equal(s.calls.filter(x=>x.update).length,1);s.resolveUpdate({data:{user:{id:'student'}}});await p;await s.nodes.passwordForm.onsubmit(event);assert.equal(s.calls.filter(x=>x.update).length,1);});
test('weak password restores save control and keeps content',async()=>{const s=page({updateError:'weak_password'});await s.nodes.verifyLink.onclick();s.nodes.newPassword.value=s.nodes.confirmPassword.value='password1';await s.nodes.passwordForm.onsubmit({preventDefault(){}});assert.equal(s.nodes.savePassword.disabled,false);assert.equal(s.nodes.newPassword.value,'password1');assert.match(s.nodes.passwordStatus.textContent,/mais forte/);});
test('native invalid password form never sends update',async()=>{const s=page({valid:false});await s.nodes.verifyLink.onclick();await s.nodes.passwordForm.onsubmit({preventDefault(){}});assert.equal(s.calls.filter(x=>x.update).length,0);});
test('password scripts parse and recovery page has no-referrer and noindex',()=>{new vm.Script(fs.readFileSync(__dirname+'/../student-access.js','utf8'));const html=fs.readFileSync(__dirname+'/../senha.html','utf8');assert.match(html,/no-referrer/);assert.match(html,/noindex,nofollow/);assert.match(html,/autocomplete="new-password"/);});
function adminScreen(options={}){
 const nodes={};for(const id of ['studentPasswordUrl','studentAccessStatus','generateStudentPasswordUrl','copyStudentPasswordUrl'])nodes[id]={value:'',disabled:false,textContent:'',focus(){},select(){}};
 const calls=[];let resolve,close;const form={innerHTML:'',querySelector:s=>nodes[s.slice(1)]||null};const modal={open:false,showModal(){this.open=true},close(){this.open=false;close?.()},addEventListener(event,fn){close=fn;}};
 const c={URL,URLSearchParams,location:{href:'https://telagomidia.github.io/Luan-Guiron-/admin.html'},students:[{id:student,full_name:'Aluno QA',active:options.inactive!==true}],view:{querySelector:()=>null},document:{querySelector:()=>({textContent:''}),createElement:()=>({})},modal,form,esc:x=>x,toast:message=>calls.push({toast:message}),navigator:{clipboard:{writeText:async value=>{calls.push({copied:value});}}},LG_AUTH:{deadline:operation=>operation()},sb:{functions:{invoke:(name,args)=>{calls.push({invoke:name,args});return options.pending?new Promise(r=>resolve=r):Promise.resolve(options.result||{data:{url:'https://telagomidia.github.io/Luan-Guiron-/senha.html#token_hash='+'a'.repeat(64)}});}}}};
 c.window=c;vm.createContext(c);vm.runInContext(fs.readFileSync(__dirname+'/../student-access.js','utf8'),c);return{c,nodes,calls,modal,resolve:value=>resolve(value)};
}
test('panel generates on demand then copies only after explicit click',async()=>{const s=adminScreen();s.c.studentPasswordLink(student);assert.equal(s.calls.length,0);await s.nodes.generateStudentPasswordUrl.onclick();assert.equal(s.calls[0].args.body.student_id,student);assert.equal(s.calls.filter(x=>x.copied).length,0);await s.nodes.copyStudentPasswordUrl.onclick();assert.ok(s.calls.find(x=>x.copied));s.modal.close();assert.equal(s.nodes.studentPasswordUrl.value,'');});
test('panel blocks inactive student and foreign generated URL',async()=>{let s=adminScreen({inactive:true});s.c.studentPasswordLink(student);assert.equal(s.calls.filter(x=>x.invoke).length,0);s=adminScreen({result:{data:{url:'https://evil.test/senha.html#token_hash=bad'}}});s.c.studentPasswordLink(student);await s.nodes.generateStudentPasswordUrl.onclick();assert.equal(s.nodes.studentPasswordUrl.value,'');assert.match(s.nodes.studentAccessStatus.textContent,/válido/);});
test('panel prevents duplicate generation while waiting',async()=>{const s=adminScreen({pending:true});s.c.studentPasswordLink(student);const p=s.nodes.generateStudentPasswordUrl.onclick();await s.nodes.generateStudentPasswordUrl.onclick();assert.equal(s.calls.filter(x=>x.invoke).length,1);s.resolve({data:{url:'https://telagomidia.github.io/Luan-Guiron-/senha.html#token_hash='+'a'.repeat(64)}});await p;});
test('panel ignores link returned after closing modal',async()=>{const s=adminScreen({pending:true});s.c.studentPasswordLink(student);const p=s.nodes.generateStudentPasswordUrl.onclick();s.modal.close();s.resolve({data:{url:'https://telagomidia.github.io/Luan-Guiron-/senha.html#token_hash='+'a'.repeat(64)}});await p;assert.equal(s.nodes.studentPasswordUrl.value,'');});
test('panel shows server refusal and releases generation button',async()=>{const s=adminScreen({result:{error:{context:{json:async()=>({error:'Aguarde um minuto.'})}}}});s.c.studentPasswordLink(student);await s.nodes.generateStudentPasswordUrl.onclick();assert.match(s.nodes.studentAccessStatus.textContent,/Aguarde/);assert.equal(s.nodes.generateStudentPasswordUrl.disabled,false);});
