// Optional DOM integration QA: npm install --prefix /tmp/portal-ui happy-dom@20.14.5
// HAPPY_DOM_ENTRY=/tmp/portal-ui/node_modules/happy-dom/lib/index.js node tests/portal-ui.check.mjs
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const {Window}=await import(process.env.HAPPY_DOM_ENTRY||'happy-dom');
const root=fileURLToPath(new URL('../',import.meta.url));
const window=new Window({url:'https://telagomidia.github.io/Luan-Guiron-/portal.html',settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true,disableComputedStyleRendering:true}});
window.document.write(fs.readFileSync(root+'portal.html','utf8').replace(/<script[\s\S]*?<\/script>/g,''));
window.confirm=()=>true;window.print=()=>{};
window.HTMLElement.prototype.scrollIntoView=function(){};
const profile={id:'own',full_name:'Aluno QA',email:'qa@example.invalid',phone:'',role:'student',active:true};
const plan={id:'plan',name:'Plano QA',goal:'Força',active:true};
const exercise={id:'exercise',exercise_name:'Agachamento',target_sets:2,rep_min:8,rep_max:12,target_rir:0,rest_seconds:60};
const workout={id:'workout',name:'Treino A',exercises:[exercise]};
const assessment={id:'assessment',assessed_at:'2026-10-08',weight_kg:70,body_fat_pct:20,bioimpedance_pdf_path:'own/report.pdf'};
let recordCalls=0,saveAnamCalls=0,failRecord=true,pendingResolve;
const api={profile:async()=>profile,plans:async()=>[plan],plan:async()=>({plan,workouts:[workout]}),sessions:async()=>[],assessments:async()=>[assessment,{...assessment,id:'previous',assessed_at:'2026-09-01',weight_kg:71}],anamnesis:async()=>null,photos:async()=>[{id:'p1',photo_date:'2026-10-08',view:'front',storage_path:'own/now.png'},{id:'p2',photo_date:'2026-09-01',view:'front',storage_path:'own/before.png'}],guidance:async()=>[{title:'Orientação QA',body:'<script>unsafe</script>',created_at:'2026-10-08'}],assessment:async()=>({assessment,circ:null,skin:null,strength:[],vo2:[],stages:[]}),signed:async()=> 'https://storage.test/private?token=qa',record:async()=>{recordCalls++;if(failRecord)throw{code:'request_timeout'};return new Promise(r=>pendingResolve=r);},saveAnam:async()=>{saveAnamCalls++;return{id:'anam'};},updateProfile:async values=>({id:'own',...values}),password:async()=>{}};
window.LG_AUTH={createClient:()=>({}),access:async()=>({user:{id:'own'},profile}),sessionExpired:()=>false,message:()=> 'Falha',deadline:fn=>fn()};
for(const f of ['portal-model.js','portal-views.js'])window.eval(fs.readFileSync(root+f,'utf8'));
window.LG_PORTAL={...window.LG_PORTAL,createApi:()=>api};
window.eval(fs.readFileSync(root+'portal-app.js','utf8'));
const doc=window.document,one=s=>{const node=doc.querySelector(s);assert.ok(node,'Missing '+s);return node;};
const settle=async()=>{for(let i=0;i<12;i++)await new Promise(r=>setTimeout(r,0));};
const click=async s=>{one(s).click();await settle();};
const route=async page=>click('[data-page="'+page+'"]');
const fill=(s,value)=>{one(s).value=value;one(s).dispatchEvent(new window.Event('input',{bubbles:true}));};
await settle();assert.match(one('#content').textContent,/Olá, Aluno/);
await route('training');await click('[data-plan]');assert.match(one('#content').textContent,/Agachamento/);assert.match(one('#content').textContent,/RIR 0/);
await click('#printTraining');assert.match(one('#printArea').textContent,/Agachamento/);
await click('#recordWorkout');fill('[data-reps]','10');one('[data-completed]').checked=true;
await click('#recordSession button[type="submit"]');assert.equal(recordCalls,1);assert.match(one('[data-form-status]').textContent,/confirmar/);assert.equal(one('[data-reps]').value,'10');assert.equal(one('#recordSession button[type="submit"]').disabled,false);
failRecord=false;one('#recordSession button[type="submit"]').click();await settle();one('#recordSession').dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));await settle();assert.equal(recordCalls,2);assert.equal(one('[data-page="home"]').disabled,true);pendingResolve({id:'session'});await settle();assert.match(one('#recordSession').textContent,/Sessão registrada/);
await route('history');assert.match(one('#content').textContent,/ainda não registrou/);
await route('assessments');await click('[data-assessment]');await click('#openBio');assert.equal(one('#actionStatus a').href,'https://storage.test/private?token=qa');
await route('progress');assert.ok(doc.querySelector('svg'));assert.equal(doc.querySelectorAll('#photoComparison img').length,2);
await route('anamnesis');fill('[name="training_goal"]','Ganhar força');for(let i=0;i<7;i++)one('[name="parq_'+i+'"]').value='no';one('[name="reviewed"]').checked=true;await click('#anamForm button[type="submit"]');assert.equal(saveAnamCalls,1);assert.match(one('[data-form-status]').textContent,/disponível/);fill('[name="training_goal"]','Novo objetivo');await click('#anamForm button[type="submit"]');assert.equal(saveAnamCalls,2);
await route('guidance');assert.match(one('#content').textContent,/<script>unsafe<\/script>/);assert.equal(doc.querySelector('#content script'),null);
await route('profile');fill('#profileName','Nome atualizado');await click('#profileForm button[type="submit"]');assert.match(one('#profileForm [data-form-status]').textContent,/atualizados/);fill('#profileName','Nome atualizado novamente');await click('#profileForm button[type="submit"]');assert.match(one('#profileForm [data-form-status]').textContent,/atualizados/);
fill('#profilePassword','unsaved-password');fill('#profileName','Outra alteração');await click('#profileForm button[type="submit"]');window.confirm=()=>false;await route('home');assert.ok(doc.querySelector('#passwordUpdate'),'Saving profile must not discard another dirty form');window.confirm=()=>true;
let guidanceResolve;api.guidance=()=>new Promise(r=>guidanceResolve=r);await route('guidance');await route('history');guidanceResolve([{title:'Late response',body:'stale'}]);await settle();assert.match(one('#content').textContent,/Meu histórico/);assert.ok(!one('#content').textContent.includes('Late response'));
api.plans=async()=>{throw{code:'request_timeout'}};await route('training');assert.match(one('#content').textContent,/Não foi possível abrir/);assert.ok(doc.querySelector('#retryPortal'));
console.log('PASS: eight routes, workout prescription/print, session failure/retry/double submit, history empty, private PDF, evolution/photos, anamnesis repeated edits, XSS escaping, profile repeated edits, dirty form protection, stale navigation response, visible query failure');
await window.happyDOM.close();
