const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function load(){const c={URL,Date,AbortController,setTimeout,clearTimeout,LG_AUTH:{deadline:fn=>fn()}};c.window=c;vm.createContext(c);for(const f of ['anamnesis-schema.js','portal-model.js','portal-views.js'])vm.runInContext(fs.readFileSync(__dirname+'/../'+f,'utf8'),c);return c;}
const c=load(),M=c.LG_PORTAL,V=c.LG_PORTAL_VIEWS;
const row=()=>({exercise_id:'e1',set_number:'1',reps:'10',load_kg:'0',rir:'0',completed:true});
test('actual series preserve zero and comma decimals',()=>{const r=row();r.load_kg='12,5';assert.equal(M.normalizeSets([r])[0].load_kg,12.5);assert.equal(M.normalizeSets([row()])[0].rir,0);});
test('unchecked sets are ignored and optional load stays null',()=>{const r=row();r.load_kg='';const out=M.normalizeSets([r,{...row(),completed:false}]);assert.equal(out.length,1);assert.equal(out[0].load_kg,null);});
for(const [key,value]of [['reps',''],['reps','1.2'],['reps','0'],['set_number','51'],['load_kg','-1'],['rir','11'],['exercise_id','']])test('invalid series '+key+'='+value,()=>assert.throws(()=>M.normalizeSets([{...row(),[key]:value}]),/./));
test('empty or duplicate series cannot be saved',()=>{assert.throws(()=>M.normalizeSets([]));assert.throws(()=>M.normalizeSets([row(),row()]));});
const anam=()=>({...Object.fromEntries(M.parqQuestions.map((_,i)=>['parq_'+i,'no'])),training_goal:' Strength ',sleep_hours:'7,5',reviewed:'on'});
test('anamnesis whitelists fields and requires review and all answers',()=>{const p=M.anamPayload({...anam(),role:'trainer',student_id:'foreign'},'id','own');assert.equal(p.student_id,'own');assert.equal(p.role,undefined);assert.equal(p.training_goal,'Strength');assert.equal(p.sleep_hours,7.5);assert.equal(Object.keys(p.parq_answers).length,7);for(const change of [{reviewed:''},{parq_2:''},{training_goal:''},{sleep_hours:'25'}])assert.throws(()=>M.anamPayload({...anam(),...change},'id','own'));});
function client(result={data:[]}){const calls=[];const q=new Proxy({then(resolve,reject){return Promise.resolve(result).then(resolve,reject);}}, {get(target,key){if(key==='then')return target.then.bind(target);return(...args)=>{calls.push([key,...args]);return q;};}});return{calls,from:t=>{calls.push(['from',t]);return q;},rpc:(...args)=>{calls.push(['rpc',...args]);return q;}};}
for(const method of ['plans','sessions','assessments','photos','guidance','anamnesis','profile'])test(method+' query explicitly scopes student',async()=>{const s=client(),api=M.createApi(s,'own');await api[method]();assert.ok(s.calls.some(x=>x[0]==='eq'&&x[1]==='student_id'&&x[2]==='own'||x[0]==='eq'&&x[1]==='id'&&x[2]==='own'));});
test('profile selection excludes private teacher observations',async()=>{const s=client();await M.createApi(s,'own').profile();assert.ok(!s.calls.find(x=>x[0]==='select')[1].includes('observations'));});
test('record calls atomic RPC and requires same returned UUID',async()=>{const s=client({data:{id:'session'}});await M.createApi(s,'own').record('session','workout',new Date().toISOString(),'note',[row()]);const args=s.calls.find(x=>x[0]==='rpc');assert.equal(args[1],'record_student_workout');assert.equal(args[2].p_sets[0].load_kg,0);assert.equal(args[2].p_student_id,undefined);await assert.rejects(()=>M.createApi(client({data:{id:'other'}}),'own').record('session','workout',new Date().toISOString(),'', [row()]),e=>e.code==='unconfirmed');});
test('future session never sends a write',async()=>{const s=client();await assert.rejects(()=>M.createApi(s,'own').record('session','workout',new Date(Date.now()+86400000).toISOString(),'', [row()]));assert.equal(s.calls.length,0);});
test('anamnesis retries same ID and preserves legacy answers',async()=>{const s=client({data:{id:'id',student_id:'own'}});await M.createApi(s,'own').saveAnam(anam(),'id',{legacy:'value'});const p=s.calls.find(x=>x[0]==='upsert')[1];assert.equal(p.id,'id');assert.equal(p.answers.legacy,'value');});
test('private signed URLs have a short lifetime and own folder restriction',async()=>{const calls=[],api=M.createApi({storage:{from:b=>({createSignedUrl:async(...args)=>{calls.push([b,...args]);return{data:{signedUrl:'https://storage.test/file?token=qa'}};}})}},'own');assert.match(await api.signed('progress-photos','own/photo.png'),/^https:/);assert.equal(calls[0][2],300);for(const args of [['public','own/a'],['progress-photos','foreign/a'],['progress-photos','own/../a']])await assert.rejects(()=>api.signed(...args));assert.equal(calls.length,1);});
test('profile update sends only safe fields and confirms owner',async()=>{let body;const api=M.createApi({functions:{invoke:async(name,args)=>{body=args.body;return{data:{profile:{id:'own'}}};}}},'own');await api.updateProfile({full_name:'Name',phone:'1',birth_date:'',sex:'',role:'trainer',id:'foreign'});assert.equal(body.role,undefined);assert.equal(body.id,undefined);assert.deepEqual(Object.keys(body),['full_name','phone','birth_date','sex']);});
test('password verifies identity and preserves literal password',async()=>{let password;const api=M.createApi({auth:{getUser:async()=>({data:{user:{id:'own'}}}),updateUser:async args=>{password=args.password;return{data:{user:{id:'own'}}};}}},'own');await api.password('  password  ','  password  ');assert.equal(password,'  password  ');await assert.rejects(()=>api.password('password','different'));});
test('changed identity cannot update password',async()=>{let called=false;const api=M.createApi({auth:{getUser:async()=>({data:{user:{id:'foreign'}}}),updateUser:()=>called=true}},'own');await assert.rejects(()=>api.password('password','password'));assert.equal(called,false);});
test('workout view escapes malicious text and preserves prescriptions including zero',()=>{const html=V.training({plan:{name:'<script>alert(1)</script>',notes:'<img onerror=alert(1)>'},workouts:[{name:'A',exercises:[{exercise_name:'<img>',target_sets:3,rep_min:8,rep_max:12,target_rir:0,rest_seconds:0,execution_notes:'slow',notes:'note'}]}]},'Student');assert.ok(!html.includes('<script>'));assert.match(html,/&lt;img/);assert.match(html,/8–12/);assert.match(html,/>0<\/td>/);assert.match(html,/slow/);assert.match(html,/note/);assert.equal(V.reps({rep_max:12}),'Até 12');});
test('assessment report displays stored data, stages and escapes notes',()=>{const html=V.assessment({assessment:{weight_kg:0,notes:'<script>bad</script>'},circ:{waist:85},skin:{triceps:12},strength:[],vo2:[],stages:[]},'Name');assert.match(html,/0 kg/);assert.match(html,/85/);assert.ok(!html.includes('<script>'));});
test('progress graph requires two measurements and avoids nonfinite data',()=>{assert.match(V.progression([{weight_kg:70}],'weight_kg','Peso','kg'),/duas avaliações/);const html=V.progression([{weight_kg:71,assessed_at:'2026-10-02'},{weight_kg:70,assessed_at:'2026-10-01'}],'weight_kg','Peso','kg');assert.match(html,/<svg/);assert.ok(!html.includes('NaN'));});
async function edge(options={}){const {studentProfileHandler}=await import('../supabase/functions/student-profile/handler.mjs');const writes=[];const query={select(){return this;},eq(){return this;},maybeSingle:async()=>({data:options.profile||{role:'student',active:true}})};const update={eq(k,v){writes.push(['eq',k,v]);return this;},select(){return this;},single:async()=>options.noMatch?{error:{}}:{data:{id:'own'}}};return{writes,handler:studentProfileHandler({caller:()=>({auth:{getUser:async()=>options.invalid?{error:{}}:{data:{user:{id:'own'}}}},from:()=>query}),admin:{from:()=>({update:values=>{writes.push(['update',values]);return update;}})}})};}
const req=(body={},extra={})=>new Request('https://edge.test',{method:'POST',headers:{Authorization:'Bearer token',Origin:'https://telagomidia.github.io'},body:JSON.stringify({full_name:'Name',...body}),...extra});
test('server profile update enforces owner and role even with forged fields',async()=>{const s=await edge();const res=await s.handler(req({id:'foreign',role:'trainer',active:false,email:'evil'}));assert.equal(res.status,200);assert.equal(s.writes[0][1].role,undefined);assert.equal(s.writes[0][1].email,undefined);assert.ok(s.writes.some(x=>x[0]==='eq'&&x[1]==='id'&&x[2]==='own'));assert.equal(res.headers.get('Cache-Control'),'no-store');});
for(const [name,options,status]of [['invalid auth',{invalid:true},401],['trainer',{profile:{role:'trainer',active:true}},403],['inactive',{profile:{role:'student',active:false}},403],['unconfirmed save',{noMatch:true},409]])test('profile server rejects '+name,async()=>assert.equal((await(await edge(options)).handler(req())).status,status));
for(const body of [{full_name:''},{birth_date:'2026-02-30'},{birth_date:'2099-01-01'},{sex:'invalid'},{phone:'x'.repeat(41)}])test('profile server validates '+JSON.stringify(body),async()=>{const s=await edge();assert.equal((await s.handler(req(body))).status,400);assert.equal(s.writes.length,0);});
test('profile server rejects missing auth and wrong origin',async()=>{const s=await edge();assert.equal((await s.handler(req({}, {headers:{}}))).status,401);assert.equal((await s.handler(req({}, {headers:{Origin:'https://evil.test'}}))).status,403);assert.equal(s.writes.length,0);});
