const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const root=__dirname+'/../';
function element(value='') {return {value,disabled:false,textContent:'',innerHTML:'',dataset:{},attrs:{},setAttribute(k,v){this.attrs[k]=v;}};}
function setup(options={}) {
 const calls=[],toasts=[],results=options.results||[],nodes=new Map();
 const form=element(),modal=element(),header=element();modal.open=false;modal.showModal=()=>modal.open=true;modal.close=()=>modal.open=false;modal.oncancel=null;modal.querySelectorAll=()=>[header];
 form.elements={};form.controls=[];form.reportValidity=()=>options.valid!==false;
 Object.defineProperty(form,'innerHTML',{get(){return this.html||''},set(v){this.html=v;nodes.clear();form.controls=[];form.elements={};for(const m of v.matchAll(/<(input|select|textarea|button|p|div)\b([^>]*)>/g)){const attrs=m[2],id=attrs.match(/id="([^"]+)"/)?.[1],name=attrs.match(/name="([^"]+)"/)?.[1];const e=element();e.disabled=/\bdisabled\b/.test(attrs);if(id)nodes.set('#'+id,e);if(name)form.elements[name]=e;if(['input','select','textarea','button'].includes(m[1]))form.controls.push(e);if(attrs.includes('data-training-status'))nodes.set('[data-training-status]',e);if(attrs.includes('type="submit"'))nodes.set('button[type="submit"]',e);} if(form.elements.student_id)form.elements.student_id.value='student';}});
 form.querySelector=s=>nodes.get(s)||null;form.querySelectorAll=()=>form.controls;form.appendChild=e=>nodes.set('[data-training-status]',e);
 const c={AbortController,setTimeout,clearTimeout,Date,navigator:{onLine:true,clipboard:{writeText:async()=>{}}},
  document:{querySelector:s=>s==='#mt'?element():s==='#form'?form:null,createElement:()=>element(),querySelectorAll:()=>[]},
  form,modal,students:[{id:'student',full_name:'Aluno QA'}],loadStudents:async()=>{},studentOptions:()=>'<option value="student">Aluno QA</option>',
  esc:s=>String(s??'').replaceAll('<','&lt;'),toast:s=>toasts.push(s),openTrainingPlan:async id=>calls.push({opened:id}),renderWorkout:async id=>calls.push({rendered:id}),
  FormData:class{constructor(target){this.values=Object.entries(target.elements).filter(([,e])=>!e.disabled).map(([k,e])=>[k,e.value]);}[Symbol.iterator](){return this.values[Symbol.iterator]();}},
  sb:{rpc:(name,args)=>{calls.push({rpc:name,args});return builder();},from:table=>{calls.push({table});return builder();}}
 };
 function builder(){const b={};for(const method of ['insert','update','delete','eq','select','single','order','maybeSingle'])b[method]=(...args)=>{calls.push({method,args});return b;};b.abortSignal=signal=>{calls.push({signal});return b;};b.then=(r,j)=>{let result=results.shift();if(options.wait)return options.wait.then(r,j);return (result instanceof Error?Promise.reject(result):Promise.resolve(result||{})).then(r,j);};return b;}
 c.window=c;vm.createContext(c);vm.runInContext(fs.readFileSync(root+'training-save.js','utf8'),c);
 return {c,form,modal,header,nodes,calls,toasts,api:c.LG_TRAINING};
}
function payload(){return {plan_name:'QA',starts_on:'',ends_on:'',workouts:[{name:'Treino A',exercises:[{exercise_name:'Supino',sets:3,rep_min:8,rep_max:12,rir:0,rest_seconds:0}]}]};}
test('LG JSON preserves numeric fields, zero RIR/rest and execution notes',()=>{const s=setup();let x=payload();x.workouts[0].exercises[0].execution='Controle';const out=s.api.parse(JSON.stringify(x));assert.equal(out.workouts[0].exercises[0].rir,0);assert.equal(out.workouts[0].exercises[0].rest_seconds,0);assert.equal(out.workouts[0].exercises[0].execution,'Controle');});
test('fenced JSON is supported',()=>assert.equal(setup().api.parse('```json\n'+JSON.stringify(payload())+'\n```').workouts.length,1));
test('malformed JSON reports useful validation error',()=>assert.throws(()=>setup().api.parse('{bad'),e=>e.code==='validation'&&e.message.includes('JSON')));
for(const [key,value] of [['sets',2.5],['sets',21],['rep_min',201],['rest_seconds',1.5],['rir',11],['exercise_name','']])test('reject invalid exercise '+key+value,()=>{let x=payload();x.workouts[0].exercises[0][key]=value;assert.throws(()=>setup().api.normalize(x));});
test('reject reversed repetitions and dates',()=>{const s=setup();let x=payload();x.workouts[0].exercises[0].rep_max=7;assert.throws(()=>s.api.normalize(x));x=payload();x.starts_on='2026-10-20';x.ends_on='2026-10-01';assert.throws(()=>s.api.normalize(x));x.starts_on='2026-02-30';assert.throws(()=>s.api.normalize(x));});
test('RIR fractional and aliases stay compatible',()=>{const s=setup();let x=s.api.exercise({name:'QA',target_sets:'3',target_rir:'1.5',execution_notes:'Técnica'});assert.equal(x.rir,1.5);assert.equal(x.sets,3);assert.equal(x.execution,'Técnica');});
test('import includes selected student and uses one atomic RPC',async()=>{const s=setup({results:[{data:'plan'}]});assert.equal(await s.api.importPlan(payload(),'student'),'plan');assert.equal(s.calls[0].args.p_payload.student_id,'student');assert.equal(s.calls.filter(x=>x.rpc).length,1);});
test('missing student never sends RPC',async()=>{const s=setup();await assert.rejects(s.api.importPlan(payload(),''));assert.equal(s.calls.length,0);});
test('empty RPC result is not confirmed as saved',async()=>{const s=setup({results:[{data:null}]});await assert.rejects(s.api.importPlan(payload(),'student'),e=>e.code==='save_unconfirmed');});
test('request catches thrown network failure and server refusal',async()=>{let s=setup({results:[new Error('network')]});await assert.rejects(s.api.importPlan(payload(),'student'));s=setup({results:[{error:{code:'P0001',message:'Aluno inválido'}}]});await assert.rejects(s.api.importPlan(payload(),'student'),e=>e.code==='P0001');assert.match(s.api.message({code:'P0001',message:'Aluno inválido'}),/Aluno inválido/);});
test('timeout releases waiting request and ignores late result',async()=>{let resolve;const s=setup({wait:new Promise(r=>resolve=r)});const query=s.c.sb.rpc('qa',{});await assert.rejects(s.api.request(query,5),e=>e.code==='save_timeout');assert.equal(s.calls.find(x=>x.signal).signal.aborted,true);resolve({data:'late'});});
test('manual exercise converts fields and confirms insert',async()=>{const s=setup({results:[{data:{id:'exercise'}}]});await s.api.saveExercise({exercise_name:' QA ',target_sets:'3',rep_min:'8',rep_max:'12',target_rir:'0',rest_seconds:'0'},'workout',2);const row=s.calls.find(x=>x.method==='insert').args[0];assert.equal(row.target_sets,3);assert.equal(row.target_rir,0);assert.equal(row.rest_seconds,0);assert.equal(row.workout_id,'workout');assert.ok(s.calls.some(x=>x.method==='select'));});
test('manual edit zero returned row cannot claim success',async()=>{const s=setup({results:[{data:null}]});await assert.rejects(s.api.saveExercise({exercise_name:'QA'},'w',1,'e'),e=>e.code==='save_unconfirmed');assert.ok(s.calls.some(x=>x.method==='eq'&&x.args[0]==='workout_id'&&x.args[1]==='w'));});
test('manual exercise invalid range sends no write',async()=>{const s=setup();await assert.rejects(s.api.saveExercise({exercise_name:'QA',rep_min:12,rep_max:8},'w',1));assert.equal(s.calls.length,0);});
test('rename confirms exact row and name',async()=>{const s=setup({results:[{data:{id:'w',name:'Treino B'}}]});await s.api.renameWorkout('w',' Treino B ');});
test('rename and delete zero rows are not successful',async()=>{let s=setup();await assert.rejects(s.api.renameWorkout('w','Treino B'));s=setup();await assert.rejects(s.api.removeExercise('e','w'));});
test('delete exercise scopes workout and surfaces foreign key error',async()=>{const s=setup({results:[{error:{code:'23503'}}]});await assert.rejects(s.api.removeExercise('e','w'));assert.ok(s.calls.some(x=>x.method==='eq'&&x.args[0]==='workout_id'));assert.match(s.api.message({code:'23503'}),/histórico/);});
async function importScreen(options={}){const s=setup(options);vm.runInContext(fs.readFileSync(root+'training-import.js','utf8'),s.c);await s.c.trainingImportForm();s.form.elements.payload.value=JSON.stringify(payload());return s;}
test('confirmation starts disabled and opens only after validation',async()=>{const s=await importScreen();const btn=s.nodes.get('#confirmImport');assert.equal(btn.disabled,true);s.nodes.get('#validateImport').onclick();assert.equal(btn.disabled,false);assert.match(s.nodes.get('#importPreview').innerHTML,/3 séries/);});
test('successful actual import form saves once and opens plan',async()=>{const s=await importScreen({results:[{data:'plan'}]});s.nodes.get('#validateImport').onclick();const event={preventDefault(){}};await s.form.onsubmit(event);await s.form.onsubmit(event);assert.equal(s.calls.filter(x=>x.rpc).length,1);assert.equal(s.modal.open,false);assert.ok(s.calls.some(x=>x.opened==='plan'));});
test('network rejection is visible inside modal and restores controls retaining JSON',async()=>{const s=await importScreen({results:[new Error('network')]});s.nodes.get('#validateImport').onclick();const before=s.form.elements.payload.value;await s.form.onsubmit({preventDefault(){}});assert.equal(s.modal.open,true);assert.equal(s.nodes.get('#confirmImport').disabled,false);assert.equal(s.form.elements.payload.value,before);assert.equal(s.nodes.get('[data-training-status]').className,'bad');assert.match(s.nodes.get('[data-training-status]').textContent,/Não foi possível salvar/);assert.equal(s.form.attrs['aria-busy'],'false');});
test('double submit does not duplicate pending RPC and blocks close',async()=>{let resolve;const s=await importScreen({wait:new Promise(r=>resolve=r)});s.nodes.get('#validateImport').onclick();const p=s.form.onsubmit({preventDefault(){}});await s.form.onsubmit({preventDefault(){}});assert.equal(s.header.disabled,true);assert.equal(s.calls.filter(x=>x.rpc).length,1);let prevented=false;s.modal.oncancel({preventDefault(){prevented=true;}});assert.equal(prevented,true);resolve({data:'plan'});await p;assert.equal(s.header.disabled,false);});
test('changing JSON or student invalidates preview',async()=>{const s=await importScreen();s.nodes.get('#validateImport').onclick();s.form.elements.payload.oninput();assert.equal(s.nodes.get('#confirmImport').disabled,true);s.nodes.get('#validateImport').onclick();s.form.elements.student_id.value='other';s.form.elements.student_id.onchange();assert.equal(s.nodes.get('#confirmImport').disabled,true);});
test('submit rejects changed student even if change event was skipped',async()=>{const s=await importScreen();s.nodes.get('#validateImport').onclick();s.form.elements.student_id.value='other';await s.form.onsubmit({preventDefault(){}});assert.equal(s.calls.length,0);assert.match(s.nodes.get('[data-training-status]').textContent,/Confira/);});
test('file JSON input loads content then requires validation',async()=>{const s=await importScreen();s.form.elements.payload.value='';await s.nodes.get('#trainingJsonFile').onchange({target:{files:[{size:100,text:async()=>JSON.stringify(payload())}]}});assert.equal(s.form.elements.payload.value,JSON.stringify(payload()));assert.equal(s.nodes.get('#confirmImport').disabled,true);s.nodes.get('#validateImport').onclick();assert.equal(s.nodes.get('#confirmImport').disabled,false);});
test('file read cannot overwrite newer typed JSON',async()=>{const s=await importScreen();let resolve;const p=s.nodes.get('#trainingJsonFile').onchange({target:{files:[{size:100,text:()=>new Promise(r=>resolve=r)}]}});s.form.elements.payload.value='new';s.form.elements.payload.oninput();resolve('old');await p;assert.equal(s.form.elements.payload.value,'new');});
test('failed view after successful save cannot create duplicate',async()=>{const s=await importScreen({results:[{data:'plan'}]});s.c.openTrainingPlan=async()=>{throw new Error('view failed')};s.nodes.get('#validateImport').onclick();await s.form.onsubmit({preventDefault(){}});await s.form.onsubmit({preventDefault(){}});assert.equal(s.calls.filter(x=>x.rpc).length,1);assert.match(s.toasts.at(-1),/Gravação concluída/);});
test('manual plan form is wired to same guarded submit',async()=>{const s=setup();const html=fs.readFileSync(root+'admin.html','utf8');const source=html.slice(html.indexOf('function planForm()'),html.indexOf('async function openTrainingPlan('));s.c.LG_PLANS={create:async v=>{s.calls.push({created:v});return 'p';}};vm.runInContext(source,s.c);s.c.planForm();s.form.elements.name.value='QA';s.form.elements.workout_count.value='3';await s.form.onsubmit({preventDefault(){}});assert.equal(s.calls.filter(x=>x.created).length,1);assert.equal(s.calls.find(x=>x.created).created.name,'QA');});
test('manual exercise form saves through guarded submit',async()=>{const s=setup({results:[{data:{id:'e'}}]});const html=fs.readFileSync(root+'admin.html','utf8');vm.runInContext(html.slice(html.indexOf('async function exerciseForm('),html.indexOf('const pendingExerciseDeletes')),s.c);await s.c.exerciseForm('w',1);s.form.elements.exercise_name.value='Supino';await s.form.onsubmit({preventDefault(){}});assert.ok(s.calls.some(x=>x.method==='insert'));assert.ok(s.calls.some(x=>x.rendered==='w'));});
test('all inline scripts and training modules parse',()=>{const html=fs.readFileSync(root+'admin.html','utf8');for(const m of html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g))if(!m[1].includes('src='))new vm.Script(m[2]);for(const file of ['config.js','training-save.js','training-import.js','plan-management.js','training-ui.js'])new vm.Script(fs.readFileSync(root+file,'utf8'));});
test('slow workout response cannot overwrite selected workout; quote in name stays in handler',async()=>{
 const s=setup(),box=element(),rename=element();box.querySelector=()=>rename;s.c.document.querySelector=()=>box;
 let finish;const wait=new Promise(r=>finish=r);s.c.sb.from=table=>{let id;const b={select(){return b},eq(k,v){id=v;return b},order(){return b},single(){return b},then(r,j){const data=table==='workouts'?{id,name:id==='b'?"Treino O'Brien":'Treino A'}:[];return (id==='a'?wait.then(()=>({data})):Promise.resolve({data})).then(r,j)}};return b;};
 const html=fs.readFileSync(root+'admin.html','utf8');vm.runInContext(html.slice(html.indexOf('async function renderWorkout('),html.indexOf('const pendingWorkoutChanges')),s.c);
 s.c.renameWorkout=(...args)=>s.calls.push({rename:args});const a=s.c.renderWorkout('a');await s.c.renderWorkout('b');rename.onclick();assert.deepEqual(s.calls.at(-1).rename,['b',"Treino O'Brien"]);const displayed=box.innerHTML;finish();await a;assert.equal(box.innerHTML,displayed);assert.ok(!box.innerHTML.includes('onclick="renameWorkout'));
});
test('native invalid form does not start save request',async()=>{const s=await importScreen({valid:false});s.nodes.get('#validateImport').onclick();await s.form.onsubmit({preventDefault(){}});assert.equal(s.calls.length,0);assert.equal(s.modal.open,true);});
